In [1]:
from sklearn.datasets import make_classification
from sklearn.utils import resample
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data  = make_classification(n_samples=1000, n_classes=2, random_state=23)

In [3]:
data

(array([[ 0.13232492,  0.33301267, -0.47925379, ..., -0.0372263 ,
         -0.55258414,  1.06965921],
        [ 1.89262246, -2.15538261, -0.39412158, ...,  1.69835282,
          0.09410361,  0.6390785 ],
        [ 0.50954567,  1.18669387,  0.95928732, ..., -0.54129521,
         -0.37482805, -2.18116821],
        ...,
        [-0.82153409,  0.61710388,  0.70239459, ..., -0.86275256,
         -0.56508439, -0.95485774],
        [ 0.61390331, -1.0616424 ,  0.88654963, ...,  0.99460724,
          0.17655184, -1.3007415 ],
        [-1.09364982, -0.25169781, -0.56959243, ..., -1.44205158,
         -0.86953376,  0.85196588]]),
 array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
        0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
        1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
        1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
        0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
        0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
        0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
        0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
        0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
        1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
        1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
        0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
        1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
        1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 1, 0, 0, 1, 0, 1, 0, 0, 1]))

In [5]:
df = pd.DataFrame(data[0], columns=[f"feature_{i}" for i in range(len(data[0][0]))])

In [6]:
df

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19
0,0.132325,0.333013,-0.479254,2.473071,-0.966725,0.493880,-0.247309,0.439594,-0.270557,1.506381,1.425326,-1.279706,1.825841,-0.764205,-0.104804,0.432687,2.300789,-0.037226,-0.552584,1.069659
1,1.892622,-2.155383,-0.394122,0.329241,0.390517,-1.404813,-1.215084,-0.310300,0.258698,-0.880988,-1.330219,0.217687,0.270797,0.159286,0.938478,0.392049,-0.449108,1.698353,0.094104,0.639079
2,0.509546,1.186694,0.959287,1.342229,-2.059967,-0.423093,-0.377241,-0.991911,-1.039653,-0.123355,-1.266389,-0.137042,-0.245330,0.356423,0.331232,-0.860039,1.462760,-0.541295,-0.374828,-2.181168
3,1.492415,1.043185,0.021732,-0.475620,1.041533,-0.127060,0.872141,0.017853,1.430772,0.194683,-1.085951,-1.780806,-1.064841,0.484594,1.076660,-0.021658,-0.813202,-0.541893,1.127384,-0.034973
4,0.485449,-0.190927,-0.800216,-0.108393,-1.856932,0.967366,-0.392703,-0.883419,-0.685578,0.777258,-0.806652,0.919138,-0.157322,-1.676752,0.524323,0.809670,-1.121761,-0.329087,-1.349292,1.206833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,-1.030286,1.078716,1.335299,-0.916411,0.474113,0.461051,-0.160864,1.828266,0.197674,-0.712917,0.238680,-1.245754,-0.911477,0.554306,-1.105743,-1.370168,0.307115,-0.339652,0.192328,-1.886998
996,-1.288221,1.132577,-0.432915,-0.465875,0.011375,-0.038766,0.323366,0.031350,-1.247558,0.924941,1.811024,0.376365,-0.420680,1.219997,0.089217,0.410570,-0.136770,-1.322066,-1.683873,0.835263
997,-0.821534,0.617104,0.702395,-0.123714,1.089481,1.612707,1.165593,1.067099,0.593014,0.355985,-1.441057,-0.829265,-1.354036,-0.114174,1.019220,-0.726419,3.823261,-0.862753,-0.565084,-0.954858
998,0.613903,-1.061642,0.886550,-0.125047,0.087675,1.218613,-1.115572,1.080081,0.697543,-0.830303,0.113996,-1.008243,-0.546744,-0.502358,-1.631960,-0.902488,-0.437639,0.994607,0.176552,-1.300742
999,-1.093650,-0.251698,-0.569592,1.793252,0.256770,0.417992,0.359678,-0.648519,0.167817,-1.059194,-2.627076,0.868639,0.722315,-0.515020,-0.322334,0.577384,-0.337556,-1.442052,-0.869534,0.851966

In [7]:
df["target"] = data[1]

In [8]:
df.shape

(1000, 21)

In [9]:
df.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,target
0,0.132325,0.333013,-0.479254,2.473071,-0.966725,0.493880,-0.247309,0.439594,-0.270557,1.506381,...,-1.279706,1.825841,-0.764205,-0.104804,0.432687,2.300789,-0.037226,-0.552584,1.069659,1
1,1.892622,-2.155383,-0.394122,0.329241,0.390517,-1.404813,-1.215084,-0.310300,0.258698,-0.880988,...,0.217687,0.270797,0.159286,0.938478,0.392049,-0.449108,1.698353,0.094104,0.639079,1
2,0.509546,1.186694,0.959287,1.342229,-2.059967,-0.423093,-0.377241,-0.991911,-1.039653,-0.123355,...,-0.137042,-0.245330,0.356423,0.331232,-0.860039,1.462760,-0.541295,-0.374828,-2.181168,0
3,1.492415,1.043185,0.021732,-0.475620,1.041533,-0.127060,0.872141,0.017853,1.430772,0.194683,...,-1.780806,-1.064841,0.484594,1.076660,-0.021658,-0.813202,-0.541893,1.127384,-0.034973,0
4,0.485449,-0.190927,-0.800216,-0.108393,-1.856932,0.967366,-0.392703,-0.883419,-0.685578,0.777258,...,0.919138,-0.157322,-1.676752,0.524323,0.809670,-1.121761,-0.329087,-1.349292,1.206833,1

In [10]:
from sklearn.decomposition import PCA

In [11]:
pca = PCA(n_components=5)

In [15]:
new_df = pca.fit_transform(df.drop("target", axis=1))

In [22]:
new_df

array([[-0.80231443,  1.35979261,  0.60038861, -2.0141562 , -0.708196  ],
       [-0.89105723, -0.19180729, -0.15031889,  1.54584073, -0.19745879],
       [ 1.83094442, -1.60127586,  0.76928544,  0.60144607, -0.06118341],
       ...,
       [ 1.86162199,  0.18523732, -0.42080189,  0.02592162,  2.45517867],
       [ 2.18181407,  0.2374073 , -0.06567291, -1.18475899,  0.38178655],
       [-1.31976293, -0.37743698,  1.13490062,  0.27272037,  0.2644522 ]])

In [23]:
x = new_df 
y = df["target"]

In [27]:
new = np.random.rand(20)

In [29]:
new

array([0.62526105, 0.07976098, 0.36714877, 0.35549014, 0.6760318 ,
       0.07470308, 0.07133969, 0.22173976, 0.02113971, 0.90208404,
       0.54032932, 0.45015452, 0.74130096, 0.3151439 , 0.44590346,
       0.72602634, 0.43804332, 0.42782719, 0.63199944, 0.24727455])

In [30]:
pca.transform([new])

array([[-0.27393591,  0.4934595 , -0.21235473,  0.20008641, -0.17959249]])

In [35]:
data[0]

array([[ 0.13232492,  0.33301267, -0.47925379, ..., -0.0372263 ,
        -0.55258414,  1.06965921],
       [ 1.89262246, -2.15538261, -0.39412158, ...,  1.69835282,
         0.09410361,  0.6390785 ],
       [ 0.50954567,  1.18669387,  0.95928732, ..., -0.54129521,
        -0.37482805, -2.18116821],
       ...,
       [-0.82153409,  0.61710388,  0.70239459, ..., -0.86275256,
        -0.56508439, -0.95485774],
       [ 0.61390331, -1.0616424 ,  0.88654963, ...,  0.99460724,
         0.17655184, -1.3007415 ],
       [-1.09364982, -0.25169781, -0.56959243, ..., -1.44205158,
        -0.86953376,  0.85196588]])